### PR TITLE
websitification

### PR DESCRIPTION
**Pull request by nevrome**
made it a website

### CODE REVIEW

**Comment by nevrome** [comment]
Any remarks on that @MartinHinz?

**Comment by MartinHinz** [comment]
Changed slightly the Statement, removed the link to the members. We should make the members only public on a webpage when they have agreed on being part of the SIG :-)

**Comment by MartinHinz** [comment]
Otherwise I am very grateful for your work and appreciated very much this step towards a proper website!

**Comment by MartinHinz** [comment]
I am fine with that, if you agree with my alterations, we might merge it into production!?

**Pull request merged**
